### ISSUE TITLE
Pickle support for Rllib implementation

### ISSUE THREAD

**Issue by ML-IEE** [BDonnot/lightsim2grid#13]
As far as I can see, the lightsim2grid does not support pickle() currently. In order to use lightsim2grid within a rllib environment, it would be usefull to make it pickable. 

Is there a future plan to include pickle within lightsim2grid?

**Comment by BDonnot** [comment]
Hello,
Thanks for this issue :-)

We will do our best to deliver it as soon as possible, but it is unlikely to come before the end of the neurips competition unless someone knows the "pybind11" package (hence the "help wanted") good enough to help us in this process

Benjamin

**Comment by BDonnot** [comment]
It's now done in version 0.3.0 :-)

If you upgrade to this version this should work perfectly hopefully

**Comment by ML-IEE** [comment]
@BDonnot I imlemented the upgraded version and it works perfectly with Ray and Rllib. Thank you very much
