### ISSUE TITLE
Compilation issue on mac

### ISSUE THREAD

**Issue by marota** [BDonnot/lightsim2grid#2]
In the installation procedure, everything worked fine on my macbook pro until the last 'pip install -U .'

I get this error
clang: error: unknown argument: '-fext-numeric-literals'
    error: command '/usr/bin/clang' failed with exit status 1

my gcc version is:
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.0 (clang-1100.0.33.16)

**Comment by BDonnot** [comment]
Apprently bug has been fixed. I close the issue.
