### ISSUE TITLE
Bug install MacOs

### ISSUE THREAD

**Issue by marota** [BDonnot/lightsim2grid#22]
[python setup_bugLightSim.pdf](https://github.com/BDonnot/lightsim2grid/files/6189149/python.setup_bugLightSim.pdf)
[python setup build_bugLightSim.pdf](https://github.com/BDonnot/lightsim2grid/files/6189150/python.setup.build_bugLightSim.pdf)

## Environment
 - Grid2op version: `1.4.0` (**eg** 1.4.0)
 - lightsim version: `0.5.0` (**eg** 0.5.0)
 - System: `osx`
 - Additional system information

**Note**: If the bug concerns an installation issue, you have to provide us with the output of:
```commandline
python3 setup.py build
```
AND
```commandline
pip install -U .
```

## Bug description

error when running python setup.py build
In file included from src/GridModel.h:31:
src/DataTrafo.h:66:17: error: call to constructor of 'cplx_type' (aka 'complex<double>') is ambiguous
                h({0., 0.})

### Command line

```bash
# command line used if any 
```

### Code snippet

```python
import lightsim2grid

... # Some code 
```

## Current output

```
The output of the code snippet above
```

## Expected output

```
The expected output and/or expected behavior description
```

**Comment by BDonnot** [comment]
This should have been solved on branch bd-dev, i am not pushing it to master until i can confirm the fix will not break the windows compilation :-)
